name=pypilot-pilots-logic
version=0.1.0
author=Mikhail Grushinskiy
maintainer=Mikhail Grushinskiy
sentence=Compiled pypilot pilot logic library for pypilot data models.
paragraph=Source priority, gains and pypilot pilot command logic for Linux and Arduino.
category=Signal Input/Output
architectures=*
includes=pypilot_pilots_logic.hpp
depends=pypilot-data-model,pypilot-algorithms,pypilot-servo-protocol,pypilot-syslib
