name: arduino
on:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: pypilot-pilots-logic
      - uses: actions/checkout@v4
        with:
          repository: bareboat-necessities/pypilot-data-model
          path: pypilot-data-model
      - uses: actions/checkout@v4
        with:
          repository: bareboat-necessities/pypilot-algorithms
          path: pypilot-algorithms
      - uses: arduino/setup-arduino-cli@v2
      - name: Install AVR platform
        run: arduino-cli core install arduino:avr
      - name: Compile example
        run: arduino-cli compile --fqbn arduino:avr:mega --libraries pypilot-pilots-logic --libraries pypilot-data-model --libraries pypilot-algorithms pypilot-pilots-logic/examples/arduino/PilotsLogicExample
